import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavbarContainer } from "@/components/navbar/NavbarContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex antialiased overflow-y-hidden text-white bg-[#0e0c0c]`}
      >
        <NavbarContainer />
        <div className="w-full p-2 h-screen">
          <div className="border bg-[#151515] p-14 border-[#5C5C5C] overflow-y-auto rounded-xl h-[98vh]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
